### ISSUE TITLE
Unable to update any note

### ISSUE THREAD

**Issue by therj** [samresh9/protectedText#36]
## Existing note does not get updated

Reproducible at https://protected.samresh.com.np/

- Encrypt some content with a secret key
- Save note passing encrypted content and hash
- Encrypt different content to get a different hash and encrypted content
- Pass new hash and note to POST /notes api existing id - the response contains old data.
- Get /notes/<note-id> also returns old data

**Comment by samresh9** [comment]
Bug fixed with new release
